"""Add is_active flags for soft deletion

Revision ID: 0b06c70b8cb3
Revises: a9f82c422760
Create Date: 2026-06-11 22:49:33.709613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b06c70b8cb3'
down_revision = 'a9f82c422760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        
    op.execute("UPDATE clients SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE departments SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE employees SET is_active = true WHERE is_active IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
