"""Add superadmin and company active status

Revision ID: 0e30fa17f2ad
Revises: 66a7fe2220b7
Create Date: 2026-06-09 17:06:00.758873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e30fa17f2ad'
down_revision = '66a7fe2220b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
