"""Make company_id and role_id nullable for user

Revision ID: a9f82c422760
Revises: dbcc6143291e
Create Date: 2026-06-09 21:19:04.324501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f82c422760'
down_revision = 'dbcc6143291e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
