"""Add is_invoiced to Expense

Revision ID: e25431d5546f
Revises: f7c3142b984a
Create Date: 2026-06-02 17:33:30.377795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25431d5546f'
down_revision = 'f7c3142b984a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_invoiced', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('is_invoiced')

    # ### end Alembic commands ###
